### ISSUE TITLE
Ego vehicle spawn failed during closed-loop simulation

### ISSUE THREAD

**Issue by georgeliu233** [Thinklab-SJTU/Bench2Drive#30] opened 2024-07-15 06:42 UTC
Hi,

When the simulation beginned at the 16th scenario:
![fe10967f32e629f639d2bd32effec45](https://github.com/user-attachments/assets/5b2161fa-53a8-4429-badd-1521645fda96)
The ego vehicle failed to be spawned, and the simulator crashed directly. 
Can you help with this issue? Seems some other social vehicle occupied the spawn point.

Best
Haochen

**Comment by jayyoung0802** [comment] 2024-07-15 07:23
Hi, It may be caused by environmental randomness. Please try a few more times. And if this problem occurs frequently, provided more details about this route.

**Comment by georgeliu233** [comment] 2024-07-19 07:24
hi, thanks for the reply! I've also frequently encountered the following issue:
![img_v3_02cu_ccb17430-f52f-40c2-8524-f8386d55b06g](https://github.com/user-attachments/assets/d9b8f397-4fde-4fd8-84ef-0cecf9278d93)
The engine may frequently crash

**Comment by jayyoung0802** [comment] 2024-07-20 07:12
This seems to have been running for a while. The crash should be caused by the agent's behavior. This route is marked as failed. Please skip this route.

**Closed** 2024-07-31 10:38 UTC
